{% set version = "10.7.0" %}

package:
  name: stripe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stripe/stripe-{{ version }}.tar.gz
  sha256: 9edadbda8b0ab5945a8d6a3b58d4f0d14c8f4e7784f5bd7e73ab85fe360145ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6
    - requests >=2.20
    - typing_extensions >=4.5.0

test:
  imports:
    - stripe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stripe/stripe-python
  summary: Python bindings for the Stripe API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
