{% set version = "10.11.0" %}

package:
  name: stripe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stripe/stripe-{{ version }}.tar.gz
  sha256: d18e1b498331fefd7738f7f72a8c0e852d7b933be9639604f81c8d575f44a1d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6
    - requests >=2.20
    - typing_extensions >=4.5.0

test:
  imports:
    - stripe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stripe/stripe-python
  summary: Python bindings for the Stripe API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
