{% set version = "11.4.0" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: stripe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/stripe/stripe-{{ version }}.tar.gz
  sha256: dbb629dd7a86ad1c66a42ca636da4fdbb5ce6a16e34d843bd123c46e804b15fe

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - requests >=2.20
    - typing_extensions >=4.5.0

test:
  imports:
    - stripe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/stripe/stripe-python
  summary: Python bindings for the Stripe API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
