{% set version = "10.6.0" %}

package:
  name: stripe
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/stripe/stripe-{{ version }}.tar.gz
  sha256: 41ccb0ada5928d89530ed06d17a71bfbf5f4ea4f2324e30d8d636a2ab7180a74

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6
    - requests >=2.20
    - typing_extensions >=4.5.0

test:
  imports:
    - stripe
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stripe/stripe-python
  summary: Python bindings for the Stripe API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
