# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "12.0.0"

package:
  name: stripe
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/stripe/stripe-${{ version }}.tar.gz
  sha256: 1bc64192b6bd853fa75e2246ad553baa28e27e348eb2c3336b4d8b021d27aae5

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - requests >=2.20
    - typing_extensions >=4.5.0

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: stripe

about:
  summary: Python bindings for the Stripe API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/stripe/stripe-python

extra:
  recipe-maintainers:
    - bollwyvl
