# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "14.3.0"

package:
  name: stripe
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/stripe/stripe-${{ version }}.tar.gz
  sha256: 4c76137d741bd43e8bb433a596c198ca20f4cdf17a8fe04604faf37c74b01978

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - flit-core >=3.11,<4
  run:
    - python >=${{ python_min }}
    - requests >=2.20
    - typing_extensions >=4.5.0

tests:
  - python:
      imports: stripe
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*

about:
  summary: Python bindings for the Stripe API
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/stripe/stripe-python

extra:
  recipe-maintainers:
    - bollwyvl
